version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=weebproject
      - POSTGRES_USER=LizRelDev
      - POSTGRES_PASSWORD=istalrij123
    ports:
      - 5432:5432
    restart: always
  weebproject:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: always
